import { ItemNameEnum } from './item-name.enum';

export const allowedItemsPerSeller: Record<string, ItemNameEnum[]> = {
  FARMER: [
    ItemNameEnum.WHEAT,
    ItemNameEnum.BEETROOT,
    ItemNameEnum.CARROT,
    ItemNameEnum.POTATO,
    ItemNameEnum.PUMPKIN_BLOCK,
    ItemNameEnum.WATERMELON_BLOCK,
  ],
  BUTCHER: [
    ItemNameEnum.RAW_CHICKEN,
    ItemNameEnum.RAW_PORK,
    ItemNameEnum.RAW_RABBIT,
    ItemNameEnum.COAL,
    ItemNameEnum.RAW_BEEF,
    ItemNameEnum.RAW_MUTTON,
    ItemNameEnum.DRIED_KELP_BLOCK,
    ItemNameEnum.SWEET_BERRIES,
  ],
  FISHERMAN: [
    ItemNameEnum.STRING,
    ItemNameEnum.COAL,
    ItemNameEnum.RAW_COD,
    ItemNameEnum.RAW_SALMON,
    ItemNameEnum.TROPICAL_FISH,
    ItemNameEnum.PUFFERFISH,
    ItemNameEnum.BOAT,
  ],
  LIBRARIAN: [
    ItemNameEnum.PAPER,
    ItemNameEnum.BOOK,
    ItemNameEnum.INK_SAC,
    ItemNameEnum.BOOK_AND_QUILL,
    ItemNameEnum.LABEL,
  ],
  ARMORER: [
    ItemNameEnum.IRON_BOOTS,
    ItemNameEnum.IRON_CHESTPLATE,
    ItemNameEnum.IRON_HELMET,
    ItemNameEnum.IRON_LEGGINGS,
    ItemNameEnum.IRON_INGOT,
    ItemNameEnum.LAVA_BUCKET,
    ItemNameEnum.DIAMOND_CHESTPLATE,
    ItemNameEnum.DIAMOND_HELMET,
    ItemNameEnum.SHIELD,
  ],
  TOOLSMITH: [
    ItemNameEnum.COAL,
    ItemNameEnum.STONE_AXE,
    ItemNameEnum.STONE_SHOVEL,
    ItemNameEnum.STONE_PICKAXE,
    ItemNameEnum.STONE_HOE,
  ],
  SHEPHERD: [
    ItemNameEnum.SCISSORS,
    ItemNameEnum.LAPIS_BLOCK,
    ItemNameEnum.BLUE_CARPET,
    ItemNameEnum.WHITE_CARPET,
    ItemNameEnum.RED_CARPET,
    ItemNameEnum.GREEN_CARPET,
    ItemNameEnum.BLUE_BED,
    ItemNameEnum.RED_BED,
    ItemNameEnum.YELLOW_BED,
    ItemNameEnum.WHITE_BANNER,
    ItemNameEnum.WHITE_WOOL,
    ItemNameEnum.BLACK_WOOL,
    ItemNameEnum.BROWN_WOOL,
  ],
  LEATHERWORKER: [
    ItemNameEnum.LEATHER,
    ItemNameEnum.LEATHER_BOOTS,
    ItemNameEnum.LEATHER_HELMET,
    ItemNameEnum.LEATHER_LEGGINGS,
    ItemNameEnum.LEATHER_CHESTPLATE,
    ItemNameEnum.FLINT,
    ItemNameEnum.LEATHER_HORSE_ARMOR,
    ItemNameEnum.LEATHER_HORSE_SADDLE,
  ],
  CLERIC: [
    ItemNameEnum.ROTTEN_FLESH,
    ItemNameEnum.GOLD_INGOT,
    ItemNameEnum.RABBIT_FOOT,
    ItemNameEnum.GLOWSTONE_BLOCK,
    ItemNameEnum.ENDER_PEARL,
    ItemNameEnum.GLASS_BOTTLE,
  ],
  CARTOGRAPHER: [
    ItemNameEnum.PAPER,
    ItemNameEnum.MAP,
    ItemNameEnum.COMPASS,
    ItemNameEnum.ITEM_FRAME,
    ItemNameEnum.WHITE_BANNER,
  ],
  FLETCHER: [
    ItemNameEnum.STICK,
    ItemNameEnum.FLINT,
    ItemNameEnum.BOW,
    ItemNameEnum.STRING,
    ItemNameEnum.ARROW,
    ItemNameEnum.CROSSBOW,
    ItemNameEnum.TRIPWIRE_HOOK,
  ],
  WEAPONSMITH: [
    ItemNameEnum.COAL,
    ItemNameEnum.IRON_AXE,
    ItemNameEnum.IRON_SWORD,
    ItemNameEnum.IRON_INGOT,
    ItemNameEnum.FLINT,
    ItemNameEnum.DIAMOND_AXE,
    ItemNameEnum.DIAMOND_SWORD,
  ],
  MASON: [
    ItemNameEnum.CLAY,
    ItemNameEnum.BRICK,
    ItemNameEnum.CHISELED_STONE_BRICK,
    ItemNameEnum.STONE_BRICK,
    ItemNameEnum.QUARTZ,
    ItemNameEnum.CHISELED_QUARTZ_BRICK,
  ],
};
