services:
  backend:
    build: ./backend
    ports:
      - "3003:3003"
    env_file:
      - ./backend/.env
    volumes:
      - ./public:/app/public

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend