export enum EmailEnum {
  FLAGGED = 'FLAGGED',
  FLAGGED_ADMIN = 'FLAGGED_ADMIN',
  BANNED = 'BANNED',
  BANNED_ADMIN = 'BANNED_ADMIN',
  RECOVERY_REQUEST = 'RECOVERY_REQUEST',
  RECOVERY_APPROVE = 'RECOVERY_APPROVE',
}
