import { ItemNameEnum } from '../../src/items/enums/item-name.enum';
import { SellerTypeEnum } from '../../src/user/enums/seller-type.enum';

export const ITEM_ICON_MAP: Record<ItemNameEnum, string> = {
  [ItemNameEnum.WHEAT]: 'wheat.png',
  [ItemNameEnum.BEETROOT]: 'beetroot.png',
  [ItemNameEnum.CARROT]: 'carrot.png',
  [ItemNameEnum.POTATO]: 'potato.png',
  [ItemNameEnum.PUMPKIN_BLOCK]: 'pumpkin_block.png',
  [ItemNameEnum.WATERMELON_BLOCK]: 'watermelon_block.png',
  [ItemNameEnum.RAW_CHICKEN]: 'raw_chicken.png',
  [ItemNameEnum.RAW_PORK]: 'raw_pork.png',
  [ItemNameEnum.RAW_RABBIT]: 'raw_rabbit.png',
  [ItemNameEnum.COAL]: 'coal.png',
  [ItemNameEnum.RAW_BEEF]: 'raw_beef.png',
  [ItemNameEnum.RAW_MUTTON]: 'raw_mutton.png',
  [ItemNameEnum.DRIED_KELP_BLOCK]: 'dried_kelp_block.png',
  [ItemNameEnum.SWEET_BERRIES]: 'sweet_berries.png',
  [ItemNameEnum.STRING]: 'string.png',
  [ItemNameEnum.RAW_COD]: 'raw_cod.png',
  [ItemNameEnum.RAW_SALMON]: 'raw_salmon.png',
  [ItemNameEnum.TROPICAL_FISH]: 'tropical_fish.png',
  [ItemNameEnum.PUFFERFISH]: 'pufferfish.png',
  [ItemNameEnum.BOAT]: 'boat.png',
  [ItemNameEnum.PAPER]: 'paper.png',
  [ItemNameEnum.BOOK]: 'book.png',
  [ItemNameEnum.INK_SAC]: 'ink_sac.png',
  [ItemNameEnum.BOOK_AND_QUILL]: 'book_and_quill.png',
  [ItemNameEnum.LABEL]: 'label.png',
  [ItemNameEnum.MAP]: 'map.png',
  [ItemNameEnum.COMPASS]: 'compass.png',
  [ItemNameEnum.ITEM_FRAME]: 'item_frame.png',
  [ItemNameEnum.IRON_BOOTS]: 'iron_boots.png',
  [ItemNameEnum.IRON_CHESTPLATE]: 'iron_chestplate.png',
  [ItemNameEnum.IRON_HELMET]: 'iron_helmet.png',
  [ItemNameEnum.IRON_LEGGINGS]: 'iron_leggings.png',
  [ItemNameEnum.IRON_INGOT]: 'iron_ingot.png',
  [ItemNameEnum.LAVA_BUCKET]: 'lava_bucket.png',
  [ItemNameEnum.DIAMOND_CHESTPLATE]: 'diamond_chestplate.png',
  [ItemNameEnum.DIAMOND_HELMET]: 'diamond_helmet.png',
  [ItemNameEnum.SHIELD]: 'shield.png',
  [ItemNameEnum.DIAMOND_AXE]: 'diamond_axe.png',
  [ItemNameEnum.DIAMOND_SWORD]: 'diamond_sword.png',
  [ItemNameEnum.IRON_AXE]: 'iron_axe.png',
  [ItemNameEnum.IRON_SWORD]: 'iron_sword.png',
  [ItemNameEnum.STONE_AXE]: 'stone_axe.png',
  [ItemNameEnum.STONE_SHOVEL]: 'stone_shovel.png',
  [ItemNameEnum.STONE_PICKAXE]: 'stone_pickaxe.png',
  [ItemNameEnum.STONE_HOE]: 'stone_hoe.png',
  [ItemNameEnum.BOW]: 'bow.png',
  [ItemNameEnum.ARROW]: 'arrow.png',
  [ItemNameEnum.CROSSBOW]: 'crossbow.png',
  [ItemNameEnum.TRIPWIRE_HOOK]: 'tripwire_hook.png',
  [ItemNameEnum.STICK]: 'stick.png',
  [ItemNameEnum.SCISSORS]: 'scissors.png',
  [ItemNameEnum.LAPIS_BLOCK]: 'lapis_block.png',
  [ItemNameEnum.BLUE_CARPET]: 'blue_carpet.png',
  [ItemNameEnum.WHITE_CARPET]: 'white_carpet.png',
  [ItemNameEnum.RED_CARPET]: 'red_carpet.png',
  [ItemNameEnum.GREEN_CARPET]: 'green_carpet.png',
  [ItemNameEnum.BLUE_BED]: 'blue_bed.png',
  [ItemNameEnum.RED_BED]: 'red_bed.png',
  [ItemNameEnum.YELLOW_BED]: 'yellow_bed.png',
  [ItemNameEnum.WHITE_BANNER]: 'white_banner.png',
  [ItemNameEnum.WHITE_WOOL]: 'white_wool.png',
  [ItemNameEnum.BLACK_WOOL]: 'black_wool.png',
  [ItemNameEnum.BROWN_WOOL]: 'brown_wool.png',
  [ItemNameEnum.LEATHER]: 'leather.png',
  [ItemNameEnum.LEATHER_BOOTS]: 'leather_boots.png',
  [ItemNameEnum.LEATHER_HELMET]: 'leather_helmet.png',
  [ItemNameEnum.LEATHER_LEGGINGS]: 'leather_leggings.png',
  [ItemNameEnum.LEATHER_CHESTPLATE]: 'leather_chestplate.png',
  [ItemNameEnum.FLINT]: 'flint.png',
  [ItemNameEnum.LEATHER_HORSE_ARMOR]: 'leather_horse_armor.png',
  [ItemNameEnum.LEATHER_HORSE_SADDLE]: 'leather_horse_saddle.png',
  [ItemNameEnum.ROTTEN_FLESH]: 'rotten_flesh.png',
  [ItemNameEnum.GOLD_INGOT]: 'gold_ingot.png',
  [ItemNameEnum.RABBIT_FOOT]: 'rabbit_foot.png',
  [ItemNameEnum.GLOWSTONE_BLOCK]: 'glowstone_block.png',
  [ItemNameEnum.ENDER_PEARL]: 'ender_pearl.png',
  [ItemNameEnum.GLASS_BOTTLE]: 'glass_bottle.png',
  [ItemNameEnum.CLAY]: 'clay.png',
  [ItemNameEnum.BRICK]: 'brick.png',
  [ItemNameEnum.CHISELED_STONE_BRICK]: 'chiseled_stone_brick.png',
  [ItemNameEnum.STONE_BRICK]: 'stone_brick.png',
  [ItemNameEnum.QUARTZ]: 'quartz.png',
  [ItemNameEnum.CHISELED_QUARTZ_BRICK]: 'chiseled_quartz_brick.png',
};

export const USER_ICON_MAP: Record<SellerTypeEnum, string> = {
  [SellerTypeEnum.ARMORER]: 'armorer.png',
  [SellerTypeEnum.BUTCHER]: 'butcher.png',
  [SellerTypeEnum.CARTOGRAPHER]: 'cartographer.png',
  [SellerTypeEnum.CLERIC]: 'cleric.png',
  [SellerTypeEnum.FARMER]: 'farmer.png',
  [SellerTypeEnum.FISHERMAN]: 'fisherman.png',
  [SellerTypeEnum.FLETCHER]: 'fletcher.png',
  [SellerTypeEnum.LEATHERWORKER]: 'leatherworker.png',
  [SellerTypeEnum.LIBRARIAN]: 'librarian.png',
  [SellerTypeEnum.MASON]: 'mason.png',
  [SellerTypeEnum.SHEPHERD]: 'shepherd.png',
  [SellerTypeEnum.TOOLSMITH]: 'toolsmith.png',
  [SellerTypeEnum.WEAPONSMITH]: 'weaponsmith.png',
};

export const BUYER_ICON: string = 'nitwit.png';
export const MANAGER_ICON: string = 'alex.png';
export const ADMIN_ICON: string = 'steve.png';
