import { ItemName } from './ItemName.ts';

export const allowedItemsPerSeller: Record<string, ItemName[]> = {
  FARMER: [
    ItemName.WHEAT,
    ItemName.BEETROOT,
    ItemName.CARROT,
    ItemName.POTATO,
    ItemName.PUMPKIN_BLOCK,
    ItemName.WATERMELON_BLOCK,
  ],
  BUTCHER: [
    ItemName.RAW_CHICKEN,
    ItemName.RAW_PORK,
    ItemName.RAW_RABBIT,
    ItemName.COAL,
    ItemName.RAW_BEEF,
    ItemName.RAW_MUTTON,
    ItemName.DRIED_KELP_BLOCK,
    ItemName.SWEET_BERRIES,
  ],
  FISHERMAN: [
    ItemName.STRING,
    ItemName.COAL,
    ItemName.RAW_COD,
    ItemName.RAW_SALMON,
    ItemName.TROPICAL_FISH,
    ItemName.PUFFERFISH,
    ItemName.BOAT,
  ],
  LIBRARIAN: [
    ItemName.PAPER,
    ItemName.BOOK,
    ItemName.INK_SAC,
    ItemName.BOOK_AND_QUILL,
    ItemName.LABEL,
  ],
  ARMORER: [
    ItemName.IRON_BOOTS,
    ItemName.IRON_CHESTPLATE,
    ItemName.IRON_HELMET,
    ItemName.IRON_LEGGINGS,
    ItemName.IRON_INGOT,
    ItemName.LAVA_BUCKET,
    ItemName.DIAMOND_CHESTPLATE,
    ItemName.DIAMOND_HELMET,
    ItemName.SHIELD,
  ],
  TOOLSMITH: [
    ItemName.COAL,
    ItemName.STONE_AXE,
    ItemName.STONE_SHOVEL,
    ItemName.STONE_PICKAXE,
    ItemName.STONE_HOE,
  ],
  SHEPHERD: [
    ItemName.SCISSORS,
    ItemName.LAPIS_BLOCK,
    ItemName.BLUE_CARPET,
    ItemName.WHITE_CARPET,
    ItemName.RED_CARPET,
    ItemName.GREEN_CARPET,
    ItemName.BLUE_BED,
    ItemName.RED_BED,
    ItemName.YELLOW_BED,
    ItemName.WHITE_BANNER,
    ItemName.WHITE_WOOL,
    ItemName.BLACK_WOOL,
    ItemName.BROWN_WOOL,
  ],
  LEATHERWORKER: [
    ItemName.LEATHER,
    ItemName.LEATHER_BOOTS,
    ItemName.LEATHER_HELMET,
    ItemName.LEATHER_LEGGINGS,
    ItemName.LEATHER_CHESTPLATE,
    ItemName.FLINT,
    ItemName.LEATHER_HORSE_ARMOR,
    ItemName.LEATHER_HORSE_SADDLE,
  ],
  CLERIC: [
    ItemName.ROTTEN_FLESH,
    ItemName.GOLD_INGOT,
    ItemName.RABBIT_FOOT,
    ItemName.GLOWSTONE_BLOCK,
    ItemName.ENDER_PEARL,
    ItemName.GLASS_BOTTLE,
  ],
  CARTOGRAPHER: [
    ItemName.PAPER,
    ItemName.MAP,
    ItemName.COMPASS,
    ItemName.ITEM_FRAME,
    ItemName.WHITE_BANNER,
  ],
  FLETCHER: [
    ItemName.STICK,
    ItemName.FLINT,
    ItemName.BOW,
    ItemName.STRING,
    ItemName.ARROW,
    ItemName.CROSSBOW,
    ItemName.TRIPWIRE_HOOK,
  ],
  WEAPONSMITH: [
    ItemName.COAL,
    ItemName.IRON_AXE,
    ItemName.IRON_SWORD,
    ItemName.IRON_INGOT,
    ItemName.FLINT,
    ItemName.DIAMOND_AXE,
    ItemName.DIAMOND_SWORD,
  ],
  MASON: [
    ItemName.CLAY,
    ItemName.BRICK,
    ItemName.CHISELED_STONE_BRICK,
    ItemName.STONE_BRICK,
    ItemName.QUARTZ,
    ItemName.CHISELED_QUARTZ_BRICK,
  ],
};